name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: "Test with python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.12"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        include:
          - os: ubuntu-latest
            python-version: "3.7"
          - os: ubuntu-latest
            python-version: "3.8"
          - os: ubuntu-latest
            python-version: "3.9"
          - os: ubuntu-latest
            python-version: "3.10"
          - os: ubuntu-latest
            python-version: "3.11"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install -e .[test]
      - name: "Run tests for ${{ matrix.python-version }}"
        run: "pytest --cov=pyproject_dependencies -v tests/"
      - uses: codecov/codecov-action@v3
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
      - name: "Install dependencies"
        run: python -m pip install -e .[test]
      - run: mypy src tests
